mikebryant/ac-nh-turnip-prices

index.html, js/predictions.js, js/scripts.js
This PR introduces a new toggle for limiting results to what is possible in your first ever week of purchasing Turnips. In your first week, your buy price is regenerated on the day after your first purchase, and your pattern is locked to pattern 3 for that week.
When the toggle is enabled, any value entered into the buy price field is ignored, and we only generate the pattern 3 results.
I also renamed the descriptions to match what they are called in Ninji's reverse engineering; I thought it would be best to remain consistent with the source material.
Based on the information provided by Ninji here: 
https://twitter.com/_Ninji/status/1245097287136706561
https://gist.github.com/Treeki/85be14d297c80c8b3c0a76375743325b#file-turnipprices-cpp-L214
=> feat: Add toggle for filtering results to first ever buy

js/scripts.js
This adjusts the current querystring load to allow for shorter, more readable querystrings, which will be easier to construct from apps or spreadsheets and easier to visually parse.
Removed the double price at the start of the string that is currently there, and allows us to remove any values that have yet to be populated.
old querystring:
https://turnipprophet.io/?prices=99.99.43.40.35.31.27.0.0.0.0.0.0.0
new query string:
https://turnipprophet.io/?prices=99.43.40.35.31.27
if there are values missing in previous fields it would look like this:
https://turnipprophet.io/?prices=99.43..35.31.27
or
https://turnipprophet.io/?prices=99.43.0.35.31.27
=> Readable dynamic length querystrings

css/styles.css
This change introduces new behavior for the data table.
If the device supports a fine pointer (mouse or touchpad) and a screen
width that is less than 1400px, we will set a max height on the table
allowing the horizontal scroll bar to be easily accessable.
If the device supports a coarse input (touch) we will not set a max
height on the table, because horizontal scrolling is a simple swipe.
If the device has a screen that is wider than 1400px we will not set a
max height on the table, as there would not be a horizontal scroll bar.
=> fix: Improved data table visibility on different devices

js/predictions.js
Changes the sorting in `generate_possibilities` to have the intended effect. 
The old version worked on Firefox, but did not sort the list on Chrome because `a.weekMax < b.weekMax` does not return `-1` if `a.weekMax > b.weekMax`.
=> Provides consistent cross-browser sorting behavior.

index.html
This avoids being able to accidentally reset the form by pressing enter in one of the input fields
fixes https://github.com/mikebryant/ac-nh-turnip-prices/issues/62
=> Change reset Button to type button

index.html, js/contributors.js
This PR is built on top of the change originally made by @Trevor-Welch in https://github.com/mikebryant/ac-nh-turnip-prices/pull/75, but makes the list of contributors dynamically updated by the Github API.
=> feat: Add dynamic list of contributors

js/predictions.js
This replaces all instances of `Math.floor()` and `Math.ceil()` with a calculation that more closely matches the C++ implementation in game. In the extracted code, the all values are passed through a function `intceil()` which is implemented as...
```cpp
int intceil(float val)
{
return (int)(val + 0.99999f);
}
```
In C++ the behaviour of casting to an int results in a truncated value, not a rounded value. As such, there are situations where using JavaScript's `Math.floor()` or `Math.ceil()` can result in a value that is off by one. By using `Math.trunc()`, we can more closely represent the C++ behaviour.
I know we already have reports of calculation issues, and there is a feeling that having a wider net of possible values can reduce the number of failed predictions, but I personally feel …
=> feat: Implements a more true to game code intceil calculation

js/predictions.js
The reversed code isn't a perfect match for ARM 32-bit floating point assembly. This should allow us to cope with things that are a little out of range due to floating point weirdness
I've checked these issues, and this allows them to compute a pattern:
Fixes #74 
Fixes #96
Fixes #63
Fixes #60
Fixes #40
=> fix: Add a fudge factor

js/predictions.js
Infinity was being returned as the min and max when the price for 
Saturday PM was entered. Instead, we should just return the Saturday PM 
price for both since that sort of reflects the rest of the week, even if 
it's just a few more hours.
This fixes a bug that was introduced in my last PR, so this is my own fault to begin with. Sorry about that, hah.
=> Fix a math issue

index.html
Due to the missing `initialize` variable in `translations.js` (initialize is defined in `scripts.js`) there is a `ReferenceError: Can't find variable: initialize` being thrown breaking iOS & Safari.
Ideally the app should be compiled via RollUp or another bundler, but fixing the script order works as well.
=> Change script ordering to fix iOS & Safari

README.md
I have added a link to the Discord server in the README. Since the Discord is used for contributors to discuss, I do not think it would be wise to put it on the site so I just added its link in the README.
Closes #17
=> Add Discord link in README

css/styles.css, index.html
This is a slightly different approach to the performance fixes in #229 for #155 that allows the cloud SVGs to remain, without the animations that were heavy on lower end devices.
Fixes #155
=> Add cloud SVGs back without animation

js/predictions.js
See #90 for previous discussion. This uses the exact probabilities instead of the rounded decimals (modulo floating point error).
=> Use exact numbers for steady state probabilities

js/contributors.js
append element to the DOM too many times may cause performance issue,
so do it only once.
=> Update contributors.js for better performance

js/predictions.js
I think this fixes Issue #258.
I went through the code to get a grasp on it and while hunting for this bug, saw that when looping into this function multiple times, the value 110 was still present in the sell-prices array, not triggering the `isNaN` check on subsequent iterations.
Please review thoroughly, I'm not sure what I might break by NOT modifying this array, but to my understanding, this is the actual fix.
=> Calculate with estimated buy price without modifying original input values

js/scripts.js
When the numbers are so small then end up in e notation is pushes
everything too far to the right. Give up when it's too small to be
really useful.
Fixes #216
=> fix: Decrease precision for tiny numbers

index.html
This PR adds a numeric regex pattern to each of the price inputs to enable iOS' number pad keyboard for price entry:
=> Add iOS number pad support

js/translations.js, locales/th.json
Hi Everyone
I would like to contribute TH translation for Turnip Prophet, since I see a lot of Thai players using this app a lot.
Screenshot:
Any comment and suggestion are welcome! :)
PS. I will ask my friend to check typo and gramma for Thai word and will confirm here again!
=> feat(locale): Add TH (Thai) Translation

js/translations.js
I've noticed that there's a bit of lag whenever typing in the input fields, and thought I could help. It's not always so bad on desktop, but especially janky on mobile.
This timeout delay stops the chart from rendering until 1000ms after the last keystroke, and helps ensure that sets of data can be input without re-rendering the chart after each keystroke.
=> adding delay after user input to prevent jank as chart refreshes

js/translations.js
Fixes https://github.com/mikebryant/ac-nh-turnip-prices/issues/314
Since radio buttons are subject to both the `document.input` event and the `input[type = radio].change` event the content is updated twice every time a radio group's value is changed.
I did not remove the change event altogether; although it should work , [MDN ](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/input_event) says: 
> For <input> elements with type=checkbox or type=radio, the input event should fire whenever a user toggles the control, per the HTML5 specification. However, historically this has not always been the case. Check compatibility, or use the change event instead for elements of these types.
So I went for a guard clause on the overall input event.
A further suggestion of mine is to bind …
=> #314 Fix Predictions are calculated twice when radios are toggled

js/translations.js
Try to fall back gracefully, using the list of fallback languages in the i18next list
Fixes #289
=> fix: Fall back to more generic languages for selection box default

css/styles.css, index.html
Ran a lighthouse scan and found some issues with 2 of the input fields on the page. 
I had to add a new selector to the CSS to get the 'language' label
=> Hook up labels to buy and language inputs

locales/pl.json
Changes:
`witam` to `witaj` (more popular form used in software)
`południe` to `popołudnie` (original word means "noon", the new one means "afternoon")
Removed unnecessary comma in `"sponsor"`
`Oh!` to `Aha!` (better expression to show a sudden realization)
`Fundatorzy` to `współautorzy` (original word means "funders", changed to "co-authors" which is a lot closer to collaborators)
=> Improve Polish translations

css/styles.css
Don't see any presentation affected in Chrome, Edge, or Firefox on both desktop and mobile. Fixes issue #331
=> remove overflow property from nook-phone css class

locales/ja.json
"チャンス" is not totally wrong, but "確率" (direct translation of "probability") sounds more natural here.
=> Change the Japanese translation of "chance"

js/contributors.js
An alternative approach to #302: Instead of a manually updated contributors list, this extends the current `getContributors` function to make paginated calls to Github API to get all contributors. 
Pros:
No manual work required when new contributors are added.
Extends code that is already working in production, so less risk.
Cons:
Makes additional calls to the Github API (n/30 calls where n = # of contributors).
Screenshots:
Current Live Site:
Proposed Change:
=> Add pagination support for fetching contributors from Github

css/styles.css, index.html, js/chart.js, js/themes.js, js/translations.js, locales/en.json
This creates a new CSS-based dark mode that automatically responds to the device's preferred mode. This fixes #317, #233, and should close #70.
I came up with the color scheme myself, trying to make it an appropriate match to the light theme. I'm totally open to changes. One advantage of this method is that it's really easy to update colors.
Since there's no more need for darkmode.js, the one downside is that there's not a toggle button for folks who want to override which color scheme gets used, but it's entirely possible to set up a button again. If there's interest in that, I can figure something out!
The one thing I want to note is that there's a lot of different shadow color values - I thought about simplifying these, but ended up just leaving them in for now.
Here's some pics of …
=> CSS-based dark mode

js/scripts.js
Debugging through this failure, i found occasionally the "update" call would be triggered by 
[Language Change events](https://github.com/mikebryant/ac-nh-turnip-prices/blob/master/js/translations.js#L52-L54) before the old data had been initialized.
this would cause the previously loaded data to be replaced with an array of nulls.
This should address #375 / #381
=> Fix data loss by preventing a call to update from running before data has been initialized.

css/styles.css, js/scripts.js
This is to help the user figure out where he needs to input the price, by highlighting the input field that corresponds to "now".
For example, this is how the page will look at 18:20 on Wednesday (notice the highlighted Wednesday/PM input):
=> Highlight the input that corresponds to current moment in time

locales/es.json
In spanish, we have two possessive adjectives, "tu" and "su". The first one is used in a informal conversation, the second one in a formal conversation. All the text is based in a informal conversation, but in line 28, there is the "su" possessive adjective.
In line 72, "el" cannot be added, as the noun "Turnip Prophet" is a proper noun.
=> Fixed some sentences
