index.html
js/scripts.js

Hello,
This PR add three features requested on #2:
- saving of prices on local storage
- loading of prices from local storage on page load
- reset button to clear the form
Tell me if you need me to change some things. I tried to follow how the code was written.
Thank you.

Add saving of prices on local storage

---

css/styles.css
index.html
js/scripts.js

Love this little tool, and I thought it would be nice to make it a little easier on the eyes. This change adds some visual styling based on Material Design language, using the Materialize library.

Added a fresh coat of paint from Materialize

---

js/predictions.js

The maximum possible buy price is 110, not 109.

Fix maximum buy price

---

index.html

Remove the `<form>` so that pressing enter in input box doesn't click the
reset button. Also remove the unused type="submit".

Don't reset the form when pressing enter in the input box.

---

js/scripts.js

This makes linking to a particular price chart easier.
(I use "." as separator instead of "," so the URL looks a little nicer, URLSearchParams seems to escape "," to "%2C")

Add support to remember prices in query string.

---

index.html
js/predictions.js
js/scripts.js

Builds off of #16 and #35
I've changed it to calculate probability per-row

feat: Integrating probability

---

css/styles.css
index.html
js/predictions.js
js/scripts.js

Squashed commit of the following:
commit efffda8fc2ae9ebf5df051c33159fc4334075470
Author: Trevor Welch <welch.trevor@yahoo.com>
Date:   Wed Apr 8 19:03:49 2020 -0400
Fixed Reset Button
Fingers crossed on last commit
commit ff6b739533c20e1eb3f4942b06def9fdfcf58548
Author: Trevor Welch <welch.trevor@yahoo.com>
Date:   Wed Apr 8 18:49:54 2020 -0400
Copy Update + Radio Button Fix
Changed the copy under "First-Time Buyer" and made the selected radio button a solid fill rather than only coloring the text.
commit 95887a68b671dcf231e4e7aea6710bfe4e2eae29
Author: Trevor Welch <welch.trevor@yahoo.com>
Date:   Wed Apr 8 18:31:18 2020 -0400
Removed a Console Log
commit 84f1ef8b96730818903aaa0e12ab12be642f8bd1
Author: Trevor Welch <welch.trevor@yahoo.com>
Date:   Wed Apr 8 18:27:03 2020 -0400
Added …

Rebasing #34

---

css/styles.css
index.html

This change reduces the overall element sizes for the new UI. This was done by reducing paddings and font sizes for all inputs.

fix: Reduced overall element size throughout UI

---

index.html

This is probably obvious for others, but at first I mistakenly put in the price I bought at, but it was from my friend's island. Just adding this text might help some people.

Clarify price should be from your island

---

js/contributors.js

Accidentally left a debug statement in the contributors script. 😬

fix: Removed a debug statement left behind

---

js/predictions.js

This also makes the predicted range more strict, so won't help with all those invalid pattern issues, but should give an more accurate result.

Change prediction of rate to consider not only the previous known value

---

js/predictions.js

I doubt this would change any prediction at all, but this is more correct according to the code.

Update rate range to match intceil

---

index.html
js/scripts.js

Added text box to notify that values will not be saved.
Valid "first" options are:
yes/true/1
no/false/0.
Valid "pattern" options are:
0/fluctuating
1/large-spike
2/decreasing
3/small-spike
anything else defaults to unknown.
Test with:
https://turnipprophet.io/?pattern=large-spike&prices=90.91..93.94..&first=true

Added parameters first-time and previous-pattern.

---

js/predictions.js

Tested that the result is same as the "should report" in #95.
Fix #48, #95.

Accurate probability.

---

js/predictions.js

Fix peak_start not defined

---

css/styles.css
index.html
js/scripts.js

Inspired by #116, this implements a permalink copy button, and includes a snackbar toast message to confirm the copy has occurred.
Closes #108

feat: Permalink copy button

---

js/scripts.js

feat: Added confirm on reset all fields

---

index.html
js/scripts.js
js/translations.js
locales/en.json

feat: Taking a first stab at implementing translations

---

service-worker.js

This makes the page less likely to be in a broken state due to updated content.
Tested locally.

Fetch from internet first for service worker

---

js/predictions.js

Closes mikebryant/ac-nh-turnip-prices#43

Future Minimum Price

---

locales/zh-TW.json

Add language support for zh-TW ,Chinese (Taiwan)

Add language support for zh-TW ,Chinese (Taiwan)

---

index.html

@mikebryant As discussed in Discord I changed the App name from localized file to hard-coded because we don't want that this name is localized.

Hard-code app name

---

css/styles.css
locales/de.json

Added German translation files.
Changes inside the `styles.css` need to be applied because the cells are to tight for the German words. 😂

Added German translation

---

locales/en.json
locales/jp.json
locales/zh-CN.json
locales/zh-TW.json

Remove general.name from locale files

---

locales/it.json

Adding a candidate Italian translation. It seems fine to me in the layout (sometimes Italian may be a bit more wordy).

Add Italian translation

---

css/styles.css
index.html
js/translations.js
locales/en.json
locales/zh-CN.json
locales/zh-TW.json

https://github.com/mikebryant/ac-nh-turnip-prices/issues/136
The selector at the bottom of the page.

Add a simple language selector. 

---

index.html
js/predictions.js
js/scripts.js

Extends #115
Closes #65
Closes #72

Chance by category and row

---

js/translations.js
locales/pt-BR.json

I managed to translate the website to Brazilian Portuguese, I hope this helps anyone who wants to use the website!

Add pt-BR translation

---

js/translations.js
locales/fr.json

French Localization File Added

French Localization File Added

---

js/translations.js

Hi!
Could Spanish be added to the language selection option?
Thanks ♥

Add Spanish to language selection

---

locales/es.json

fix: Improve Spanish translation of week buy price

---

locales/es.json

I spotted a couple of typos checking the Spanish live version and changed them.

ES language fixes

---

js/predictions.js
js/scripts.js

In preparation for moving fudge_factor logic to be able to first run the predictor without, and only add fudge if there's no results

refactor: Move Predictor into class

---

index.html

This was very subtle, and is apparently causing performance issues on lower-end devices
Fixes #155

fix: Remove animation

---

js/translations.js
locales/ko.json

This PR adds a korean translation.

Add korean translation

---

js/predictions.js
js/scripts.js

fix: prevent variable being declared globally

---

js/translations.js
locales/hu.json

Add Hungarian translation

---

js/translations.js
locales/nl.json

Thought I'd contribute since I've enjoyed using this tool for a while now.

Add Dutch translations

---

index.html
locales/en.json

feat: Add link to GitHub sponsors button

---

locales/zh-TW.json

fixed zh-TW,Chinese (Taiwan) wording

fixed zh-TW,Chinese (Taiwan) wording

---

locales/en.json

Suggested language fix for #214

modify language for clarity

---

css/styles.css

I personally found it is really hard to notice the "reset" and "permalink" buttons are buttons - because they do not have a background colour so they look like some text labels!

Added background colour to reset and permalink buttons

---

js/translations.js
locales/ca.json

Add catalan translation

---

js/predictions.js

- Use [x, x+1) instead of [x-0.5, x+0.5), ensuring that min_value() and max_value() return integers
- Fix range_of and max_value being off by epsilon
- Use improved Kahan–Babuska algorithm for floating point summation
These improvements:
- improve the accuracy of PDF by at least a factor of 2 when calculating the Irwin-Hall distribution with n=3
- fixes pdf.range_limit([pdf.min_value(), pdf.max_value()]) incorrectly mutating the PDF and returning a value that is not 1
- fixes the decreasing pattern with buy=100 incorrectly being calculated with max predictions which are 1 too high
The code used for testing the accuracy of this PDF implementation is shown below. `test_pdf_1` uses the [Irwin hall distribution](https://en.wikipedia.org/wiki/Irwin%E2%80%93Hall_distribution) with n=3, as it's …

Various improvements to PDF

---

css/styles.css
index.html

There's an additional divs for Wednesday while the other days don't.

Simplify Wednesday div, fix fat scrollbar in other browsers

---

js/translations.js
locales/gl.json

Created locale file for Galician (ISO 639-3: glg)

Galician localisation

---

locales/zh-TW.json

紀錄 is not a proper word in this sentence. Use 記錄 instead.

Fix translation in zh-TW

---

js/predictions.js
js/scripts.js

Cleaning up Predictor class by removing dependency on i18next. Moved translation logic to display function (``calculateOutput``) in script.js.
Closes #201

Decoupling Predictor class from i18next.

---

README.md

Fixing several grammatical mistakes and typos.

Copyediting of README.md

---

locales/ca.json

update catalan local with theme translations

---

index.html
locales/nl.json

This adds subsource integrity to check that the referenced remote scripts have not been modified and fixes a NL translation error

Add subsource integrity, fix NL tl error

---

css/styles.css

Colour added when hovering over input, copy & reset button. It is same colour with those option button to reduce confusion.

Add colour when hovering over the input, copy & reset button

---

js/translations.js
locales/ph.json

Did a Filipino (tagalog) translation since I have friends who prefer reading the text in Filipino. They can still cope with the english text since they _do_ play the game afterall but of course giving them options is the way to go.
Anyway I did my best in translating and here it is. There are some obvious terms that do not have true native Filipino translations. But in the Philippines, English is still used as a second language so it's pretty normal to add English jargon within Filipino statements ("tag-lish" so to speak) if needed especially with foreign terms.
Believe it or not a _lot_ of Filipinos don't even understand quite a lot of native Filipino words (since some are so "deep") and if I explicitly translate some of them here than I'm pretty sure they won't understand a big chunk of …

Filipino translation

---

js/translations.js

This is a change such that the lang attribute of html tag does not remain "en" when a non-English language is chosen.

Change lang attribute according to chosen language

---

locales/de.json

Refine German translation

---

locales/es.json
locales/pt-BR.json

Added "sponsor", "theme" and "errors" translations in Spanish and Brazilian Portuguese.

Updated translation files (es, pt-BR)

---

locales/hu.json

Add error message at lines 87-89.

Update Hungarian translation
